version: "3.1"

services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - db
    command: db:1433

  db:
    image: "mcr.microsoft.com/mssql/server"
    environment:
      SA_PASSWORD: "1gr3jA@2021"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"

  desafioapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: desafioapi
    depends_on:
      - start_dependencies
    ports:
      - "9000"
